spring:
  application:
    name: standard-task-manager-svc
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/external
          jwk-set-uri: http://localhost:8888/realms/external/protocol/openid-connect/certs
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 10000
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
---
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
---
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
---
cors:
  allowed-origin-patterns: http://localhost:3000